name: Docker build

on:
  push:
    tags:
      - 'v*'

env:
  IMAGE_NAME: outlinewiki/outline
  BASE_IMAGE_NAME: outlinewiki/outline-base

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
      is_prerelease: ${{ steps.check_prerelease.outputs.IS_PRERELEASE }}
    steps:
      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      - name: Check if prerelease
        id: check_prerelease
        run: |
          if [[ "${{ steps.version.outputs.VERSION }}" == *"-"* ]]; then
            echo "IS_PRERELEASE=true" >> $GITHUB_OUTPUT
          else
            echo "IS_PRERELEASE=false" >> $GITHUB_OUTPUT
          fi

  build-base:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64/v8
          - linux/arm/v7
          - linux/ppc64le
          - linux/s390x
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.base
          push: true
          platforms: ${{ matrix.platform }}
          tags: ${{ env.BASE_IMAGE_NAME }}:latest-${{ matrix.platform }}

  merge-base-manifests:
    needs: [prepare, build-base]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Create and push final manifest
        run: |
          TAGS="-t ${{ env.BASE_IMAGE_NAME }}:${{ needs.prepare.outputs.version }}"
          if [[ "${{ needs.prepare.outputs.is_prerelease }}" == "false" ]]; then
            TAGS="$TAGS -t ${{ env.BASE_IMAGE_NAME }}:latest"
          fi
          
          docker buildx imagetools create $TAGS \
            ${{ env.BASE_IMAGE_NAME }}:${{ needs.prepare.outputs.version }}-linux/amd64 \
            ${{ env.BASE_IMAGE_NAME }}:${{ needs.prepare.outputs.version }}-linux/arm64/v8 \
            ${{ env.BASE_IMAGE_NAME }}:${{ needs.prepare.outputs.version }}-linux/arm/v7 \
            ${{ env.BASE_IMAGE_NAME }}:${{ needs.prepare.outputs.version }}-linux/ppc64le \
            ${{ env.BASE_IMAGE_NAME }}:${{ needs.prepare.outputs.version }}-linux/s390x

  build-main:
    needs: [prepare, merge-base-manifests]
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64/v8
          - linux/arm/v7
          - linux/ppc64le
          - linux/s390x
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push main image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: ${{ matrix.platform }}
          tags: ${{ env.IMAGE_NAME }}:${{ needs.prepare.outputs.version }}-${{ matrix.platform }}

  merge-main-manifests:
    needs: [prepare, build-main]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Create and push final manifest
        run: |
          TAGS="-t ${{ env.IMAGE_NAME }}:${{ needs.prepare.outputs.version }}"
          if [[ "${{ needs.prepare.outputs.is_prerelease }}" == "false" ]]; then
            TAGS="$TAGS -t ${{ env.IMAGE_NAME }}:latest"
          fi
          
          docker buildx imagetools create $TAGS \
            ${{ env.IMAGE_NAME }}:${{ needs.prepare.outputs.version }}-linux/amd64 \
            ${{ env.IMAGE_NAME }}:${{ needs.prepare.outputs.version }}-linux/arm64/v8 \
            ${{ env.IMAGE_NAME }}:${{ needs.prepare.outputs.version }}-linux/arm/v7 \
            ${{ env.IMAGE_NAME }}:${{ needs.prepare.outputs.version }}-linux/ppc64le \
            ${{ env.IMAGE_NAME }}:${{ needs.prepare.outputs.version }}-linux/s390x
