name: Docker

on:
  push:
    tags:
      - "v*"

env:
  IMAGE_NAME: outlinewiki/outline
  BASE_IMAGE_NAME: outlinewiki/outline-base

jobs:
  build-and-push:
    runs-on: ubicloud-standard-16
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.base
          push: true
          tags: ${{ env.BASE_IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm/v7,linux/arm64

      - name: Extract tag version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build and push main image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            ${{ contains(steps.get_version.outputs.VERSION, '-') && format('{0}:{1}', env.IMAGE_NAME, steps.get_version.outputs.VERSION) || format('{0}:{1},{0}:latest', env.IMAGE_NAME, steps.get_version.outputs.VERSION) }}
